"""add final_diagnoses

Revision ID: 1b4f7323eb3c
Revises: ab98583f79c1
Create Date: 2026-05-04 16:55:22.205424

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b4f7323eb3c'
down_revision: Union[str, None] = 'ab98583f79c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_diagnoses',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'analyzing', 'done', 'failed', name='examination_status', create_type=False), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('clinical_context', sa.Text(), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=500), nullable=True),
    sa.Column('icd10', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Enum('low', 'moderate', 'high', name='final_diagnosis_confidence'), nullable=True),
    sa.Column('urgency', sa.Enum('green', 'yellow', 'red', name='final_diagnosis_urgency'), nullable=True),
    sa.Column('ai_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_report', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_diagnoses_created_by_id'), 'final_diagnoses', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_final_diagnoses_patient_id'), 'final_diagnoses', ['patient_id'], unique=False)
    op.create_table('final_diagnosis_examinations',
    sa.Column('final_diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('examination_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_diagnosis_id'], ['final_diagnoses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('final_diagnosis_id', 'examination_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final_diagnosis_examinations')
    op.drop_index(op.f('ix_final_diagnoses_patient_id'), table_name='final_diagnoses')
    op.drop_index(op.f('ix_final_diagnoses_created_by_id'), table_name='final_diagnoses')
    op.drop_table('final_diagnoses')
    # Drop enum types created in upgrade (examination_status is shared, leave it).
    sa.Enum(name='final_diagnosis_urgency').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='final_diagnosis_confidence').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
