"""add ai_summary column

Revision ID: ab98583f79c1
Revises: 2e93d86054a8
Create Date: 2026-05-01 23:01:00.822245

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab98583f79c1'
down_revision: Union[str, None] = '2e93d86054a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('examinations', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('examinations', 'ai_summary')
    # ### end Alembic commands ###
