"""add patients and examinations

Revision ID: d4c08b1c5ceb
Revises: 50fd9030bd75
Create Date: 2026-05-01 21:12:27.631515

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c08b1c5ceb'
down_revision: Union[str, None] = '50fd9030bd75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_by_id'), 'patients', ['created_by_id'], unique=False)
    op.create_table('examinations',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('XRAY', 'CT', 'MRI', name='examination_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'DONE', 'FAILED', name='examination_status'), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=False),
    sa.Column('image_mime', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('ai_report', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examinations_created_by_id'), 'examinations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_examinations_patient_id'), 'examinations', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_examinations_patient_id'), table_name='examinations')
    op.drop_index(op.f('ix_examinations_created_by_id'), table_name='examinations')
    op.drop_table('examinations')
    op.drop_index(op.f('ix_patients_created_by_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
